### ISSUE TITLE
Guests and Visitors Unable to Use Things

### ISSUE THREAD

**Issue by SekerAsar** [TVPT/VoxelGuest#102]
Aside from Guests being able in the Guest Zones, neither can use things elsewhere. It's a bit of a problem at times, especially with doors. They cant explore about 50% of a building because of it. Mono said he'd do the booty doo later, but for the sake of this being srsbiznus official stuff I submit this anyways.

Less than three, pluggineers

**Comment by nristock** [comment]
Has been fixed in d5b108eb4403733aa247af87c972fb166ae207ed
