### ISSUE TITLE
Region Module Rewrite

### ISSUE THREAD

**Issue by TheCryoknight** [TVPT/VoxelGuest#103]
I know that mono is working on this but, could we have the plans centralized here. So we can look at and analyze what needs to be done.
Thanks

**Comment by nristock** [comment]
Not sure what a rewright is but my original plans for the region module overhaul haven't changed. 
The goal is a lightweight system that is easy to extend. Therefor so-called 'RegionRules' will be introduced. A region rule is basically a class implementing an interface. If Bukkit sends a monitored event the region manager will determine which region are affected. It will then calculate which rule of which region has the highest priority and will therefor be executed. A rule's execution returns a boolean indicating whether the event should be cancelled or not.

I will post a block diagram to clarify things when I get home on Friday.

**Comment by TheCryoknight** [comment]
Well Theses are my current thoughts
http://puu.sh/4V6Jn.png
