### ISSUE TITLE
Clean up test DBs

### ISSUE THREAD

**Issue by Deamon5550** [TVPT/VoxelGuest#113]
VoxelGuest creates several test databases, I assume as part of its unit testing. Should it be part of the shutdown of these tests to clean up these temporary files?

![jenks](https://cloud.githubusercontent.com/assets/1249030/2959843/c38729e2-dab6-11e3-949c-65ef8fa1dae0.PNG)

**Comment by nristock** [comment]
I didn't think about that. Very good idea - I won't have time to implement it myself at the moment though. - You're welcome to submit a PR.
