### ISSUE TITLE
Permissions question

### ISSUE THREAD

**Issue by Spiritwo** [TVPT/VoxelGuest#18]
Is there a way to see what the permission nodes are for the individual commands?  

If not, could someone say what the permission node is for the /spawn command.

**Comment by BlockCat** [comment]
The permission node is:
voxelguest.spawn.spawn

**Comment by psanker** [comment]
We haven't compiled them completely, but you are free to look at the source. Each permission is found with the line saying "@CommandPermission(permission="perm.blah.thing")"
