### ISSUE TITLE
/who

### ISSUE THREAD

**Issue by vacante** [TVPT/VoxelGuest#19]
On the voxel box when a player does /who it gives a read out of ranks and colors but on every other server when doing this it gives a readout of [null] then player names. I was wondering if there is a way to change this and whether or not this is based in the voxel guest micro permissions or what?
Thanks

**Comment by psanker** [comment]
It currently uses a bunch of auto-generated group file names... However, sometime in the near future, I'd like to condense those all into a YAML file.

**Comment by vacante** [comment]
Is there a way to configure the /who at the moment or is that voxel box only because its very convienient when players can see ranks of other members. I you can provide a layout
For the group that would be great. I don't have many but dealing with the [null] is becoming more and more annoying if you understand.
Thanks

**Comment by psanker** [comment]
The setup is on the wiki, if you want to add group-ids and such. Check out http://voxelwiki.com/minecraft/VoxelGuest
