### ISSUE TITLE
Plugin Files Resetting to Default

### ISSUE THREAD

**Issue by thetophatbandit** [TVPT/VoxelGuest#2]
I've installed the latest version of this plugin, but whenever I try to change any settings in any of the plugin files, they instantly reset to the default config upon a restart or reload. This doesn't happen with any other plugins, so I believe the problem is within VoxelGuest.

**Comment by itsjoekent** [comment]
Try changing them by doing...
1. Shut down the server
2. Change whatever config you need to change
3. Start the server

If doing that does not work reply back telling me so

**Comment by itsjoekent** [comment]
Im going to assume this issue was fixed. If not please open a new ticket.
