### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by vacante** [TVPT/VoxelGuest#20]
Ip-banning added to the Asshat mitigator. Might be a good idea with the prevalence of hacked accounts and such.

Simplicity of it could be 
/ipban on/off
/exportbans option to export bans to bans.txt

Maybe a tempban option instead of a full ban.

**Comment by itsjoekent** [comment]
Unless your using a plugin to find a users IP in-game, the only people who know the IP are administrators viewing the console. The administrators can then banip from their, and I think you can do that in-game as well.

**Comment by vacante** [comment]
What I mean by this is to have an option to auto up based on the /ban command. Because it would be easier to manage bans that way. A adjustment to the asshatmitigator that allows the auto ip banning of players by issuing the /ban command. This would help with alt usage on servers.

**Comment by itsjoekent** [comment]
I'll just add an argument to ban their IP, see no reason to make a brand new command for something this simple and implemented. If you need/prefer I can just add a permission to IP banning

**Comment by psanker** [comment]
Yeah, the banning systems need an upgrade along with the regions system.

**Comment by vacante** [comment]
Will you also make it so when you pardon a player it will pardon their ip also? So you don't have to unban their player name and their ip address?

**Comment by psanker** [comment]
Do note: IP banning is really easy to go around. And I mean REALLY easy.
