### ISSUE TITLE
The New Helper System

### ISSUE THREAD

**Issue by ghost** [TVPT/VoxelGuest#23]
Hey there,

So let's talk about the new Helper System. This is partially a rant, but also a couple of additions I'm wondering if are possible or could be implemented in the future.

So the way I used to do things before this system was that I'd just ask in main chat, "Hey, does any guest need a review", and one or two would usually answer "Yeah, sure", and I' just teleport to them and give them a review of their work. And if I found something that was up to par, I'd send it to an Admin. Case closed.

But the new system feels to me like an assembly line, or a really formal business. It's almost like when you call a company, and you get the machine that says "If you want a review, type /wlreview into your chat box, and a Helper will be with you shortly". It feels so impersonal.

Then when that does happen, a message goes out to every single online Helper that says that "GUEST" wants a review. At that point (and maybe this is just my feeling), it feels like a competition to see who can get that review faster. It doesn't feel like how I used to do things at all, where it was laid back, and I obviously had guests that I would help (not to say that I had selective groups; you get my point). But now it just feels like I'm part of a factory or something, building guest reviews.

I like the idea of being able to type in a command to see the list of Helpers, and those who are online. I also like (although not as much) the ability to see how many reviews any guest has recieved. But I don't like the way that things are so impersonal now. I find it much harder to enjoy my experience and make friendly bonds with guests; and of course, it feels like such a race, or automated process now.

I'm almost wondering exactly why we switched to this system. From my three+ months of experience as a Helper, my old system worked perfectly fine.

As far as additions, I'd definitely like to know if it would be possible to implement a way to see who last reviewed a guest when I look at their history, and even perhaps if I can see who reviewed them all four or five times. That would be helpful. There have been at least two times I can count where a guest has done something that was fundamentally wrong, and claimed that he did so on the instruction of another Helper, but he can't remember who that person was. I'd like to know who it was so that I can speak with them, and we can be on the same page. Maybe he's understanding something I'm not.

As well as that, make a command so that when a ticket is closed, I get a notification. Right now, I have no idea who closed the ticket when until I try to accept it, only to find out that it's been closed. I'd find it helpful to have something pop on my screen that says "GUEST is being reviewed by HELPER" right when the ticket closes.

And if this new system is in fact mostly to see a history of a guest's reviews, and to see who actually is a Helper or not, then why don't we just do this:

Let me do what I used to, and just go around asking if guests need reviews, and let them say "yes". Then I can just type in /wlreview GUEST, and it'll still add that to their history. But now it can be the same personal way that it used to be, friendly and casual as ever.

**Comment by MikeMatrix** [comment]
/facepalm

EDIT: Meaning. This is not a bug report nor feature request. It's far to long and should be put in the forum.

**Comment by MikeMatrix** [comment]
Malformatted Issue
