### ISSUE TITLE
Some Caveats

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#25]
Note: These issues have been found in 1.3 and may not exist in 1.2.5 (which is what the latest dev version of VG was built for). I just figured that it can't hurt to have more information when it comes to updating/testing.

Kick/ban reasons no longer support color formatting (i.e. &cAsshat).

It is possible to set an offline password, but upon joining the game for the first time when in offline mode, the server kicks you for not having an offline mode account. Upon attempting to connect for the second time, the server does not kick you from the server, but you are frozen in place. Sending chat messages is possible, but doing so returns an error in the console. It is not possible to unlock your player.

"/freeze" does not work, mostly. It is possible to move, break blocks, and place blocks, but you are teleported back to the location you were frozen at every 10-15 seconds. This has been an issue since 1.2.5, I believe.

I received an error at one point regarding the vanish module, but I do not have details/error reports at the moment. I'll edit this section if I am able to reproduce the error. It did not have an impact on the functionality of the module.

Water buckets and lava buckets can be used in protected regions. Total bucket usage is possible. Someone, call the bucket police.

Setting spawn via "/setspawn" sets the location in which players are teleported to after typing "/spawn", but it does not define the location in which players respawn after death or spawn after first joining the game. I used VG in coordination with Commandbook at first and needed to set the spawn with both plugins to effectively have players spawning/respawning at one  location. After installing My Worlds, I no longer needed to set the spawn with Commandbook (and I had disabled the feature completely within the Commandbook configuration), but I did need to set a My Worlds spawn at the same location as my VG spawn in order to correct the issue. (This may be intentional, but these are my observations.)

**Comment by psanker** [comment]
Freeze works as long as your internet connection works properly. I would make it a variant of the "/sit" command except I don't trust sending packets directly.

The offline mode has had troubles in the past. I plan to make it better soon (if I have time).

The formatting in general needs to be better.

I've copied prz on the Spawn issue.

**Comment by Aerodog** [comment]
I've figured it out. NoCheatPlus screws with freeze and breaks it. It works better without NoCheatPlus, but you can still break blocks.

Edit: Regions allow for the placement/removal of water/lava and the brutal tearing down of paintings. -_faints_-
