### ISSUE TITLE
VoxelGuest incompatible with Multiverse?

### ISSUE THREAD

**Issue by Billyyjoee** [TVPT/VoxelGuest#26]
Multiverse seems to just say "LOLNO" to anything that VoxelGuest Cubicles try to create and will only use the terrain generator specified in the Multiverse config. Is it possible to make these two compatible and be friends? :3

**Comment by nristock** [comment]
Not sure if this bug still exists in VoxelGuest 5.x.x - needs revalidation.

**Comment by nristock** [comment]
Since nobody answered on this and I can't confirm this issue using the latest build I gonna close this.
