### ISSUE TITLE
[MOVED] Guest List Problem

### ISSUE THREAD

**Issue by MikeMatrix** [TVPT/VoxelGuest#29]
@Starjik posted (on VoxelSniper issue tracker):

Today, we had a few guests who came onto vent to get re gray listed as something has stopped them from being on the list, after further review, we re-gray listed them, it then turned out that the only guests with access are the ones which have been re gray listed, i am unsure if this is a permanent fix (i.e. they are still GL after server restart) as we have not restarted the server. I don't know if its the MC servers causing this or one of the plugins which have been updated over night to cause this.

**Comment by itsjoekent** [comment]
Is it possible with the recent restarts not shutting down properly/slow guest was not able to write the greylist?

**Comment by nristock** [comment]
Should be fixed in VG 5 now.
