### ISSUE TITLE
Gag, mute and soapbox all broken

### ISSUE THREAD

**Issue by Deamon5550** [TVPT/VoxelGuest#33]
gag: gives them the message but they can still talk just fine.
mute: Is working the way gag should be working, they can type the ungag phrase to get unmuted
soapbox: does absolutely nothing except giving me a message saying silent mod is enabled.

**Comment by psanker** [comment]
https://github.com/psanker/iSay/blob/master/src/main/java/com/patrickanker/isay/listeners/PlayerListener.java#L32

There's your answer to "mute," which actually is part of the iSay config.

**Comment by itsjoekent** [comment]
Psank can we add soapbox to iSay?

**Comment by psanker** [comment]
Yes. Though, frankly, tickets on the iSay project would be appreciated.

**Comment by nristock** [comment]
I guess that's fixed in VG5 now. I gonna close this one.

**Comment by psanker** [comment]
Actually, /soapbox is still inoperative. However, iSay has "promoted channels" which is effectively the same thing.
