### ISSUE TITLE
Issue with /list

### ISSUE THREAD

**Issue by Spiritwo** [TVPT/VoxelGuest#35]
On my server running craftbukkit v1.3.2-R3.0 with the latest version of voxelguest from github (4.2.4), when you type in the /list command it produces the following error.

http://pastie.org/5128969

Other plugins: 
BetterAnnounce
Essentials
libpsanker
PermissionsEx
PEXRank
PluginMetrics

**Comment by Spiritwo** [comment]
The issue above seems to have faded.. But now there is a new error when using the /list command:
Running on CB 1.4.2-R0.2, the error is:
http://pastie.org/5182055

**Comment by Aerodog** [comment]
Ensure that all of your groups have a group-id in their properties file.

**Comment by itsjoekent** [comment]
Is this still an issue or can I close this?

**Comment by nristock** [comment]
I guess this is fixed in VG5 now. I gonna close this.
