### ISSUE TITLE
Offline Mode Management is Totally Broken

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#37]
http://pastebin.com/3YhkdLPE

Expected Behavior:
1. My account would be recognized as having an offline password (it is not recognized, although one is set).
2. I would be able to unlock my account using that password in offline mode.
(That would be the whole purpose of this feature.)

The module hasn't been working for over a year, but I tried using it with CraftBukkit 1.3.2 (recommended build), 1.4.2 (beta build), and 1.4.4 (dev build) recently.

java version "1.7.0_01"
Java(TM) SE Runtime Environment (build 1.7.0_01-b08)
Java HotSpot(TM) 64-Bit Server VM (build 21.1-b02, mixed mode)

**Comment by MikeMatrix** [comment]
I don't even know why that module is still in there. Is so far beyond broken. I'll label this as a wontfix.
