### ISSUE TITLE
Banning Partially Broken

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#38]
Expected Behavior:
1. I type "/ban playername" (playername = portion of online player's name).
2. Online player is recognized, kicked, and banned.

The player is not recognized--if "PlayerA" is online, "/ban play" bans "play". If I type "/ban PlayerA", PlayerA is banned, but he is not kicked from the game.

This has been happening since VG 4.2.4.

java version "1.7.0_01"
Java(TM) SE Runtime Environment (build 1.7.0_01-b08)
Java HotSpot(TM) 64-Bit Server VM (build 21.1-b02, mixed mode)

**Comment by Aerodog** [comment]
Any progress with this? Banning is too much of a hassle currently.

**Comment by BlockCat** [comment]
I'll look into it.
