### ISSUE TITLE
Bug concerning disabling of modules (commands)

### ISSUE THREAD

**Issue by DukeVindzor** [TVPT/VoxelGuest#4]
I came to notice a thing when it comes to turning off features in VoxelGuest: When you turn off modules that has commands, you will turn of the command on any other plugin as well. So let's say I have Essentials and VoxelGuest, then I disable the AssHat Mitigatior module so I can use the ban feature of Essentials, however I won't be able to. When you try to use /ban (and asshat module is disabled) it will tell you unhanded command, even though /ban from essentials should be available.
It is easy to work around at the moment cause most plugins have aliases for these commands, but it will probably cause problem for a plugin one day.

**Comment by itsjoekent** [comment]
@Duke
Thanks for moving it, just trying to keep things organized.

**Comment by DukeVindzor** [comment]
Sure np

**Comment by psanker** [comment]
Sounds like an issue with Bukkit registering VoxelGuest's commands last... I think the only way to resolve this is to hack into the plugin.yml of your copy of VoxelGuest and remove the commands you wish Essentials to control.

**Comment by DukeVindzor** [comment]
Oh that should be simple enough, thanks for the tip :) I still hope it can be fixed though, I have seen other plugins do this successfully, but I guess they are coded very differently

**Comment by psanker** [comment]
It can be done using dynamic command registration, but that takes some significant Bukkit hacking, hacking I'm not sure I want to do.
