### ISSUE TITLE
/who or /list prompts an internal error

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#50]
Using the latest version of VG and CB 1.4.6. I'll provide any additional requested info.

**Comment by MikeMatrix** [comment]
Could you send us the internal error please?

**Comment by Aerodog** [comment]
http://pastie.org/private/nomoguvlyltpqiumfwjqyg

**Comment by MikeMatrix** [comment]
Which version of libpsanker do you have on your server?

**Comment by Aerodog** [comment]
The latest one. 1.4.5 I believe.

**Comment by MikeMatrix** [comment]
I cant' seem to be able to reproduce this problem.

**Comment by Aerodog** [comment]
Perhaps I have a conflicting plugin... I'll try to isolate the one causing the issue (if this is the case). I do use Commandbook, but the online-list feature is disabled and I've never had this issue in the past. Anyway, I'll keep looking.

**Comment by Aerodog** [comment]
I've figured it out. One group didn't have a group-id. My bad. Carry on.
