### ISSUE TITLE
Suggestion: Viewable ban reasons

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#53]
When a command is executed, the reason for a player's ban is shown.  
1. Admin types "/banreason playerx"
2. Server responds "playerx is banned for: reason" if he is banned or "playerx is not banned" if he isn't.

**Comment by Billyyjoee** [comment]
That actually seems like a good idea. I might take a look into it later.
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by nristock** [comment]
Yeah I like it. I have to have a look into the source since I don't think
we're saving the reason at the moment but it will be in one of the next
releases.
