### ISSUE TITLE
Latest build (i think) downloaded but it wont show up on my server :/

### ISSUE THREAD

**Issue by Oldsoldier2003** [TVPT/VoxelGuest#54]
I have downloaded Voxel and have put it in my plugins folder on my server, it is the only plugin on that server as it is one of my testing servers, yet it shows that i have no plugins installed... Help! [ VoxelSniper-5.168.0.jar is what i got]

**Comment by MikeMatrix** [comment]
This is neither the correct place to post a ticket about VoxelSniper, nor is it called "Voxel". 5.168.0 is an older version which is no longer compatible with the latest craftbukkit. For the latest version of VoxelSniper refer to http://dev.bukkit.org/server-mods/VoxelSniper
