### ISSUE TITLE
Gagging Cancelled by iSay

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#55]
Installing iSay disallows me from gagging people as their chat is still sent regardless of whether they are gagged or not. Muting via iSay works, but it is undone if they reconnect to the server. 

I cannot /cban people from the default channel (which would be useful--have a primary and a secondary default channel rather than just one so this is possible.)

(I apologize for putting this here rather, but I cannot post in the iSay issues. It does involve VG, however.)

Edit: Soapbox is affected as well.
Edit 2: The [You --> Null] bug has returned. Duck. Cover.

**Comment by MikeMatrix** [comment]
iSay is not an VoxelBox Plugin. The repository we have is a mere copy, that I have adjusted for 1.4.6.

**Comment by Aerodog** [comment]
Alright, I'll just close this.

**Comment by itsjoekent** [comment]
@Monofraps is working on a chat plugin to my knowledge. So don't worry / hold on a little!
