### ISSUE TITLE
Suggestion: Sign Lookup Command

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#56]
For example, typing "/signlookup" while standing at the coordinates 247, 90, -37 in world 'world' will search for "Location -> X:247 Y:90 Z:-37 @ world" in the sign log file and return a list of the contents of all signs that have ever been placed at those coordinates in the specified world. Additionally, perhaps the command can accept coordinate arguments, such as "/signlookup 247 90 -37" or "/signlookup x247 y90 z-37"

Possible output:

Sign history at X:247 Y:90 Z:-37 in world 'world':
[11/28  9:19:12] PLAYERA: ' Line1 ' Line Two  ' Line 1+2 ' Fourth Line '
[12/14  7:17:10] PLAYERB: ' Line1 ' Line Two  ' Line 1+2 ' Fourth Line '
[1/12  5:15:8] PLAYERA: ' Line1 ' Line Two  ' Line 1+2 ' Fourth Line '

**Comment by itsjoekent** [comment]
VoxelGuest is going under a huge re-write soon, I'll see if I can make a quick fix for this but it won't be perfect

**Comment by Aerodog** [comment]
Thanks. I forgot to add this, but can you implement a permission such as "voxelguest.signlookup" so only admins and users with permission can use it?

**Comment by itsjoekent** [comment]
That's what I was planning on doing yes
