### ISSUE TITLE
Blocks are not dropping.

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#67]
I love using the no-physics region flag on my server, but the region module cannot be used so long as this bug exists:

regardless of whether the block dropping flag is set to 0 or 1, blocks do not drop when broken if the region module is enabled.

Using VoxelGuest 5.0.0-SNAPSOT-jnks6 (latest version as of this issue).

**Comment by nristock** [comment]
Seems like a simple fix... However, it could be an incompatibility with one of your other plugins. Can we get a list?

**Comment by Aerodog** [comment]
I actually did a bit of testing and removed all plugins except commandbook, permissionsex, and some voxel plugins. The issue only existed if the region module was enabled still.

**Comment by nristock** [comment]
Which version of Guest did you use to create the region? It might be possible that your database was created using an old DB schema (we do not have auto update yet). This could result in a failing DB read operation.

**Comment by Aerodog** [comment]
Persistence was generated using the latest version of voxelguest and the region was made with the latest version as well.

**Comment by nristock** [comment]
Hmm... that's really odd.

**Comment by Aerodog** [comment]
It was fixed in an update.
