### ISSUE TITLE
Nested Regions (Region priority system)

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#72]
A small, nested region with build restriction OFF overrides a global region with build restriction ON. Players may only build in that region. A small nested region with build restriction ON does _not_ override a global region with build restriction OFF. Players may build anywhere regardless. 

I'm not sure what causes this. You may not have realized that this bug exists because it works perfectly with something like a Guest region. I want to use a region to define an area in which certain players cannot build instead (the opposite).

**Comment by nristock** [comment]
We know about this bug. 
In the current system, DENY will override ALLOW. We also know that overlapping/nested regions are a bit problematic. Therefor we will need implement a region priority system. 
However, I think for now it would be sufficient to simply let nested regions override global options.
