### ISSUE TITLE
When looking at persons review history, no comments are displayed.

### ISSUE THREAD

**Issue by ayyy** [TVPT/VoxelGuest#73]
Greetings.

When either reviewing a guest with (/hreview X) or (/hreview -h X) no comments are displayed even though there should be comments.

5.0.0-Snapshot-jnks5

**Comment by nristock** [comment]
I can only guess since I'm not the one who wrote the system. However, I think it is because of some database changes we made. Which version of Guest was used to create the persistence database file?

**Comment by ayyy** [comment]
Should've probably mentioned, its on TVB, so I don't have a clue, same thing for the other issue.
