### ISSUE TITLE
Open review, but not able to review it.

### ISSUE THREAD

**Issue by ayyy** [TVPT/VoxelGuest#74]
Greetings.

Sometimes /hreview states that there is an open review, but when trying to review the person, it says "There is no open review for "X"", don't know much info about this, might happen after a reload, but this has happened a few times now at least. Also, when trying to force close, it says there is no match.

5.0.0-Snapshot-jnks5

**Comment by nristock** [comment]
I can only guess since I'm not the one who wrote the system. However, I think it is because of some database changes we made. Which version of Guest was used to create the persistence database file?

**Comment by TheCryoknight** [comment]
This is actually a known bug witch occurs when a player logs-out with an open review. I think I have fixed this but I will do some more testing to be sure

**Comment by nristock** [comment]
If it is a know bug why didn't you open a bug report? :P I was literally one click away from pushing a "stable" release.

**Comment by TheCryoknight** [comment]
Nah it is stable, this and the other bug #73 are no longer appearing as of 5.0.0-Snapshot-jnks14.
