### ISSUE TITLE
Players instantly returning after /afk

### ISSUE THREAD

**Issue by TheCryoknight** [TVPT/VoxelGuest#75]
This is such a weird bug witch I have connected to switching worlds and chatting, though When the player re-logs it works again.

**Comment by nristock** [comment]
Go ahead and try to fix it. It's a show stopper so I'm not going to release until this is fixed.

**Comment by Aerodog** [comment]
Just something I've noticed: if you are in any way gliding (sometimes caused by flight), falling, or anything when you /afk, you will immediately return because you have moved. Maybe have a 3 second AFK requirement or something before the plugin begins detecting to return you from AFKness.

**Comment by nristock** [comment]
Yeah. I think a delay could work. However, do not use threads or tasks for this. A simple time difference check should do it.

**Comment by TheCryoknight** [comment]
Resolved.
