### ISSUE TITLE
Suggestion: Asshat Immunity

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#78]
If a group is granted a certain permission, then users in that group cannot be banned, kicked or muted. (There can be one permission for all 3 or 3 separate permissions--doesn't matter.)

i.e. Admins cannot be kicked by lower-ranked staff members and staff members cannot kick each other because both admins and the lower-ranked staff groups have _voxelguest.asshat.immune_. There would need to be a _voxelguest.asshat.immuneoverride_ permission as well so admins can kick the lower-ranked staff group.

**Comment by TheCryoknight** [comment]
Hmmm, personally I like the way it currently works, though its not truly my call.

**Comment by nristock** [comment]
Hmmm. I think we can do this since it is an addition and not a change. You are not forced to use the immune nodes.

**Comment by TheCryoknight** [comment]
Yes, but anyone with the wild card node("*") will auto inherit it.

**Comment by itsjoekent** [comment]
Have to agree with cryo on this one

**Comment by nristock** [comment]
Oh right. I didn't think about wildcard permission. What about a configuration prop (default off) to control this behaviour?

**Comment by TheCryoknight** [comment]
That would be a better option. Note: never forget about the wildcard functionality its the one thing that always throwing a wrench in permission setup. :smile:

**Comment by nristock** [comment]
Any reason you closed this?
