### ISSUE TITLE
Missing Ungag/Unmute phrase feature

### ISSUE THREAD

**Issue by TheCryoknight** [TVPT/VoxelGuest#79]
In all prior versions of VG there has been a functionality that when gagged the player could enter the ungag phrase in chat and would no longer be gagged. I personally think it should be implemented such that if the player was gagged with a flag they would not be able to ungag themselves via this method.

**Comment by nristock** [comment]
Added in d35a87088802e1ee4fe30014183fefa77bfb89f4
