### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#81]
= 1 =
The "mob spawn" and "creature spawn" region flags do not exist, but they can be configured manually in the database file. 

= 2 =
FIRE_DAMMAGE_ALLOWED("fid", "Fire damage"),

is missing the dash and should be

FIRE_DAMMAGE_ALLOWED("-fid", "Fire damage"),

= 3 =
The snow formation and suffocation damage flags do not work.
Inputting "/vregion edit test -sud:t -sf:t" does not change their values to 1; they remain 0.

There is a difference between these two; "formtion" works:

SNOW_FORMATION_ALLOWED("-sf", "Formation of snow"),
ICE_FORMATION_ALLOWED("-if", "Formtion of ice"),

Missing a thing:

SUFFOCATION_DAMMAGE_ALLOWED("-sud", ""),

= 4 =
This error randomly occurred. I do use Spigot rather than Craftbukkit and that may be why, but you might be interested.  

http://bit.ly/104O6lc

= 5 =
This is just a suggestion. Since VoxelGuest prevents nearly all interactions within a protected region, perhaps the message should say "You cannot modify this area." instead of "You cannot build here." Building is just one thing VG prevents. There's opening/closing doors, chests, pushing buttons, levers, etc.

= 6 =
Suggestion: Ability to adjust region coords?

**Comment by TheCryoknight** [comment]
For number 4 that is because banned blocks takes different parameters refer to the help for that

**Comment by Aerodog** [comment]
Oh yeah. I know that. Ignore number 4.
