### ISSUE TITLE
Usergroup Names & Colors

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#89]
VoxelGuest requires that the name of a usergroup be in the https://github.com/TVPT/VoxelGuest/blob/master/src/main/java/com/thevoxelbox/voxelguest/modules/general/command/WhoCommandExecutor.java file with a group that can be assigned a color associated with it, which means that I must adjust the group names in that file and compile the plugin to have a colored '/who' list. 

Would it be possible for "//TODO: More flexible group system" to be fulfilled in the case that a change in the code is not committed and I cannot access the source?

**Comment by nristock** [comment]
I already implemented it in my local dev branch. I have to do some more testing with a damn lot of other permission plugins before I push to master, though.
