### ISSUE TITLE
no modules load on initial startup

### ISSUE THREAD

**Issue by xemnes** [TVPT/VoxelGuest#90]
hello there, so i have decided to install voxel guest on my server but my problem is it wont start properly.

so far i have tried updating vault and testing a multitude of dev versions including the latest from jenkins and the version listed on the tvb wiki of voxel guest but to no avail =/

it seems it wont load any of the modules but the helper module

im using craftbukkit version 1.5.1 R01

i also have the latest version of vault and the latest version of pex

heres the error log including a log of what happens when i try to enable the modules from ingame:
http://pastebin.com/MRYCufT7

**Comment by nristock** [comment]
We are aware of this problem and I'm already working on figuring out what's going wrong there.

Can you provide some additional information about your environment? - OS, Java version ('java -version' output), exact Bukkit release (build number), exact VoxelGuest release (build number), etc.? I'm having trouble to reproduce the error, so these pieces of information would be quite helpful.

**Comment by xemnes** [comment]
will do, currently at uni so i will do so when i get home.

**Comment by xemnes** [comment]
debian linux
java version "1.7.0_11"
Java(TM) SE Runtime Environment (build 1.7.0_11-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.6-b04, mixed mode)

craftbukkit #2754 1.5.1-R0.2 Beta Build

voxel guest Build #112 (http://ci.thevoxelbox.com/view/VoxelPlugins/job/VoxelGuest/112/)

**Comment by nristock** [comment]
This might potentially be fixed since we are not using the morph framework anymore which seemed to cause the issue. If something similar happens again, just open a new ticket.
