### ISSUE TITLE
Entities in Regions

### ISSUE THREAD

**Issue by Aerodog** [TVPT/VoxelGuest#98]
Hi, again. In regions, it is impossible for players to break blocks or interact with any buttons, levers etc., but I was wondering if it would be possible to prevent players from attacking mobs or grabbing the attention of a mob in any way. 

I want to showcase a world that is actively used by certain players, but I don't want the visitors to interact with the world. Voxelguest blocks almost everything except for this. Visitors cannot obtain items or anything so the only thing that would need to be blocked is if any mob sees a player without modification permissions, they won't react and if any player tries to attack a mob, it is cancelled and they get the warning message that they cannot modify the area. 

Thanks! 

EDIT: I just realized that you can mount pigs/horses as well. I think having the region prevent all interactions would be incredibly useful because no other plugin developer has created such a powerful region protection plugin.

**Comment by maxnordlund** [comment]
Couldn't you just have the visitors in creative mode? Then they wont draw any mob attention. But I don't know if the rest works since VoxelGuest is designed for survival. I think it's at least worth  a test.

**Comment by Aerodog** [comment]
No because you can attack mobs in survival mode.

**Comment by nristock** [comment]
I will look into it. However, I'm on vacation right now so don't expect
immediate implementation.

**Comment by Aerodog** [comment]
Actually, I'm going to close this issue because I can use the PermissionsEx plugin extension "ModifyWorld" to do the same thing. Unfortunately, PEX is probably going to be discontinued and implementing some of the features of ModifyWorld which make it so powerful could be a good goal for the future, but it's nothing urgent now.

You would effectively create a region-based ModifyWorld which is a really attractive feature. Especially with the flags that are already in place, i.e. no-physics.
